/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
caculadora_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	datos calculadora_1_arg1;
	t_vector nulo = {0};
	printf("-----------------------------------------------------\n");
	printf("              Por favor escoge una opción: \n");
	printf("                 1.- Suma \n");
	printf("                 2.- Resta \n");
	printf("                 3.- Multiplicacion \n");
	printf("                 4.- Divison \n");
	printf("                 5.- Modulo \n");
	printf("                 6.- Potencia \n");
	printf("                 7.- Logaritmo \n");
	printf("                 8.- Producto Escalar de dos vectores\n");
	printf("                 9.- Suma de vectores(NO FUNCIONAL) \n");
	printf("-----------------------------------------------------\n");
	scanf("%i",&calculadora_1_arg1.menu);
	if ( calculadora_1_arg1.menu < 8 ){
		printf("Primer operando:\n");
		scanf("%le",&calculadora_1_arg1.valor_1);
		printf("Segundo operando\n");
		scanf("%le",&calculadora_1_arg1.valor_2);
		calculadora_1_arg1.vector_1 = nulo;
		calculadora_1_arg1.vector_2 = nulo;
		calculadora_1_arg1.solucion = nulo;
	}
	else{
		int tamanio;
		printf("Introduzca el tamaño de los vectores\n");
		scanf("%i",&tamanio);
		calculadora_1_arg1.vector_1.t_vector_len = tamanio;
		calculadora_1_arg1.vector_2.t_vector_len = tamanio;
		calculadora_1_arg1.solucion.t_vector_len = tamanio;
		calculadora_1_arg1.vector_1.t_vector_val = malloc(tamanio*sizeof(float));
		calculadora_1_arg1.vector_2.t_vector_val = malloc(tamanio*sizeof(float));
		calculadora_1_arg1.solucion.t_vector_val = malloc(tamanio*sizeof(float));
		printf("Introduzca los valores del primer vector\n");
		for (int i = 0; i<tamanio; i++){
			printf("Introduzca elementos vector1\n");
			scanf("%f",&calculadora_1_arg1.vector_1.t_vector_val[i]);
		}
		printf("Introduzca los valores del segundo vector\n");
		for (int i = 0; i<tamanio; i++){
			printf("Introduzca elementos vector2\n");
			scanf("%f",&calculadora_1_arg1.vector_2.t_vector_val[i]);
		}
		calculadora_1_arg1.valor_1 = 0;
		calculadora_1_arg1.valor_2 = 0;
	}


#ifndef	DEBUG
	clnt = clnt_create (host, Caculadora, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_1(calculadora_1_arg1, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
	if( calculadora_1_arg1.menu < 9)
		printf("Resultado: %f:",*result_1);
	else
	{
		printf("Resultado: ");
		for (int i = 0; i<calculadora_1_arg1.solucion.t_vector_len; i++){
			printf("%f   ",calculadora_1_arg1.solucion.t_vector_val[i]);
		}
	}
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	caculadora_1 (host);
exit (0);
}
