/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int t_vector_len;
	float *t_vector_val;
} t_vector;

struct datos {
	int menu;
	double valor_1;
	double valor_2;
	t_vector vector_1;
	t_vector vector_2;
	t_vector solucion;
};
typedef struct datos datos;

#define Caculadora 0x20000001
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculadora 1
extern  double * calculadora_1(datos , CLIENT *);
extern  double * calculadora_1_svc(datos , struct svc_req *);
extern int caculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculadora 1
extern  double * calculadora_1();
extern  double * calculadora_1_svc();
extern int caculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_t_vector (XDR *, t_vector*);
extern  bool_t xdr_datos (XDR *, datos*);

#else /* K&R C */
extern bool_t xdr_t_vector ();
extern bool_t xdr_datos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
