/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos (XDR *xdrs, datos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->menu))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor_1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor_2))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->vector_1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->vector_2))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->solucion))
		 return FALSE;
	return TRUE;
}
